@startuml Overview
!include .pu/C4_Container.pu

System(frontend, "Frontend", "React frontend.")
System(backend, "Backend", "Java backend")
System(idp, "Keycloak", "For OAuth/JWT")

Rel(frontend, backend, "Label", "GraphQL API requests")
Rel(backend, idp, "Label", "Token validation")
Rel(frontend, idp, "Label", "Authentication")
@enduml
